name: Alerts to Discord

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Build payload for PR events
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          cat > payload.json <<'JSON'
          {
            "username": "CI/CD Bot",
            "content": "**${{ github.repository }}**\nPR #${{ github.event.pull_request.number }} (${{ github.event.pull_request.title }})\nAction: *${{ github.event.action }}*\nBy: **${{ github.actor }}**\nURL: ${{ github.event.pull_request.html_url }}"
          }
          JSON

      - name: Build payload for push events
        if: ${{ github.event_name == 'push' }}
        run: |
          cat > payload.json <<'JSON'
          {
            "username": "CI/CD Bot",
            "content": "**${{ github.repository }}**\nPush to **${{ github.ref_name }}** by **${{ github.actor }}**\nCommit: ${{ github.sha }}\nhttps://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          }
          JSON

      - name: Send to Discord
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -sS -H "Content-Type: application/json" -X POST -d @payload.json "$WEBHOOK"
