name: CI / tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ feature/*, fix/* ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install pytest
      - run: pytest -q
